// generated by the notebook, do not edit
function automatic logic [31:0] weight_const(input int layer, input int neuron, input int idx);
  case ((layer << 12) | (neuron << 8) | idx)
    4096: return 32'h0000a174;  // L1 n0 w0
    4097: return 32'h000017af;  // L1 n0 w1
    4098: return 32'h000104cd;  // L1 n0 w2
    4099: return 32'hffff798f;  // L1 n0 w3
    4100: return 32'h0000601e;  // L1 n0 w4
    4352: return 32'h00018636;  // L1 n1 w0
    4353: return 32'h000013b4;  // L1 n1 w1
    4354: return 32'h00008134;  // L1 n1 w2
    4355: return 32'h00001567;  // L1 n1 w3
    4356: return 32'h0000188c;  // L1 n1 w4
    4608: return 32'h0000c034;  // L1 n2 w0
    4609: return 32'hffff2b0c;  // L1 n2 w1
    4610: return 32'hfffee69d;  // L1 n2 w2
    4611: return 32'h000064e0;  // L1 n2 w3
    4612: return 32'h00003355;  // L1 n2 w4
    4864: return 32'h0000e966;  // L1 n3 w0
    4865: return 32'hffff78ea;  // L1 n3 w1
    4866: return 32'h00000834;  // L1 n3 w2
    4867: return 32'hffffedb4;  // L1 n3 w3
    4868: return 32'hffff4b5e;  // L1 n3 w4
    8192: return 32'hffff662b;  // L2 n0 w0
    8193: return 32'hffffda52;  // L2 n0 w1
    8194: return 32'hffffddca;  // L2 n0 w2
    8195: return 32'h00000d48;  // L2 n0 w3
    8448: return 32'hffffc24b;  // L2 n1 w0
    8449: return 32'hffffbbdc;  // L2 n1 w1
    8450: return 32'hffff9493;  // L2 n1 w2
    8451: return 32'h00001a66;  // L2 n1 w3
    8704: return 32'hffffc7b7;  // L2 n2 w0
    8705: return 32'hffff3d44;  // L2 n2 w1
    8706: return 32'hfffe089f;  // L2 n2 w2
    8707: return 32'h0000912e;  // L2 n2 w3
    8960: return 32'h000115ec;  // L2 n3 w0
    8961: return 32'h00011b96;  // L2 n3 w1
    8962: return 32'hffff0f92;  // L2 n3 w2
    8963: return 32'hffff469e;  // L2 n3 w3
    12288: return 32'hffff279a;  // L3 n0 w0
    12289: return 32'hffffb2fe;  // L3 n0 w1
    12290: return 32'h0000d69d;  // L3 n0 w2
    12291: return 32'h0000ab3d;  // L3 n0 w3
    default: return 32'h0;
  endcase
endfunction
