// generated by the notebook, do not edit
function automatic logic [31:0] bias_const(input int layer, input int idx);
  case (layer * 16 + idx)
    16: return 32'h00000ff7;  // layer 1 neuron 0
    17: return 32'hfffee6a9;  // layer 1 neuron 1
    18: return 32'hffffe27d;  // layer 1 neuron 2
    19: return 32'hffff013a;  // layer 1 neuron 3
    32: return 32'hffff8d4c;  // layer 2 neuron 0
    33: return 32'hfffffbb0;  // layer 2 neuron 1
    34: return 32'hffffe0bc;  // layer 2 neuron 2
    35: return 32'hffff8802;  // layer 2 neuron 3
    48: return 32'h00000daa;  // layer 3 neuron 0
    default: return 32'h0;
  endcase
endfunction
