// generated by the notebook, do not edit
function automatic logic [31:0] bias_const(input int layer, input int idx);
  case (layer * 16 + idx)
    16: return 32'hffff16f7;  // layer 1 neuron 0
    17: return 32'h0000ecbf;  // layer 1 neuron 1
    18: return 32'h0000cff1;  // layer 1 neuron 2
    19: return 32'hffffee6e;  // layer 1 neuron 3
    32: return 32'hffffd635;  // layer 2 neuron 0
    33: return 32'hffffd3f9;  // layer 2 neuron 1
    34: return 32'hffff9b65;  // layer 2 neuron 2
    35: return 32'hfffffe22;  // layer 2 neuron 3
    48: return 32'h00000ebc;  // layer 3 neuron 0
    default: return 32'h0;
  endcase
endfunction
