// generated by the notebook, do not edit
function automatic logic [31:0] weight_const(input int layer, input int neuron, input int idx);
  case ((layer << 12) | (neuron << 8) | idx)
    4096: return 32'h0000a903;  // L1 n0 w0
    4097: return 32'h0000b835;  // L1 n0 w1
    4098: return 32'h0000b283;  // L1 n0 w2
    4099: return 32'hffffb576;  // L1 n0 w3
    4100: return 32'h00002b21;  // L1 n0 w4
    4352: return 32'hffff4665;  // L1 n1 w0
    4353: return 32'h00013e17;  // L1 n1 w1
    4354: return 32'h00001ad7;  // L1 n1 w2
    4355: return 32'h00001029;  // L1 n1 w3
    4356: return 32'hffffe991;  // L1 n1 w4
    4608: return 32'h00008996;  // L1 n2 w0
    4609: return 32'h00018436;  // L1 n2 w1
    4610: return 32'h00015ed9;  // L1 n2 w2
    4611: return 32'hffffbdf5;  // L1 n2 w3
    4612: return 32'hfffff206;  // L1 n2 w4
    4864: return 32'h0000bba2;  // L1 n3 w0
    4865: return 32'hffffeef6;  // L1 n3 w1
    4866: return 32'h00015aa0;  // L1 n3 w2
    4867: return 32'hffffd306;  // L1 n3 w3
    4868: return 32'h000077c0;  // L1 n3 w4
    8192: return 32'hffff8ef3;  // L2 n0 w0
    8193: return 32'h00002f4e;  // L2 n0 w1
    8194: return 32'hffff5147;  // L2 n0 w2
    8195: return 32'h000039ff;  // L2 n0 w3
    8448: return 32'h0000693b;  // L2 n1 w0
    8449: return 32'hfffe71c6;  // L2 n1 w1
    8450: return 32'h00008b51;  // L2 n1 w2
    8451: return 32'h00012e4f;  // L2 n1 w3
    8704: return 32'h00000a37;  // L2 n2 w0
    8705: return 32'h00010135;  // L2 n2 w1
    8706: return 32'hffff8234;  // L2 n2 w2
    8707: return 32'hffffc82a;  // L2 n2 w3
    8960: return 32'h00009f82;  // L2 n3 w0
    8961: return 32'h00003ae7;  // L2 n3 w1
    8962: return 32'hfffef0cd;  // L2 n3 w2
    8963: return 32'h000092f5;  // L2 n3 w3
    12288: return 32'hffff420f;  // L3 n0 w0
    12289: return 32'h0000c55b;  // L3 n0 w1
    12290: return 32'hffffecb3;  // L3 n0 w2
    12291: return 32'hffff389a;  // L3 n0 w3
    default: return 32'h0;
  endcase
endfunction
